parameters:
    reports: []
    tracker: ""
    tracker.mapping_class: ""

services:
    filesystem:
        class: Qissues\System\Filesystem

    shell:
        class: Qissues\System\Shell\BasicShell

    yaml_parser:
        class: Symfony\Component\Yaml\Parser

    yaml_builder:
        class: Symfony\Component\Yaml\Dumper

    frontmatter_parser:
        class: Qissues\Application\Input\FrontMatterParser
        arguments:
             - @yaml_parser
