parameters:
    reports: []
    console.editor: "vim"
    console.tmp_file.prefix: "qissues"
    console.browser.command:
    console.input.default_strategy: "edit"
    console.input.default_format: "frontmatter"
    console.input.default_issue_format: "frontmatter"
    console.input.default_details_format: "yaml"
    console.output.tinyview_priorities:
        5: '▲'
        4: '▴'
        3: '-'
        2: '▾'
        1: '▼'
    console.output.tinyview_colors:
        bug: "p5"
    system.storage.filename: "~/.qissues.json"

    features:
        - types
        - statuses
        - labels
        - priorities
        - metadata

    # Internal
    tracker: ""
    mapping_class: ""

services:
    model.issue_serializer:
        class: Qissues\Interfaces\Console\Output\Serializer\IssueSerializer

    model.comment_serializer:
        class: Qissues\Interfaces\Console\Output\Serializer\CommentSerializer

    system.initializer:
        class: Qissues\Application\Initializer
        arguments:
            - @container
            - @filesystem

    system.storage:
        class: Qissues\Application\Storage\LocalStorage
        arguments:
            - @filesystem
            - %system.storage.filename%

    console.shell:
        class: Qissues\System\Shell\BasicShell

    console.input.report_manager:
        class: Qissues\Interfaces\Console\Input\ReportManager
        arguments:
            - %reports%

    console.input.issue_strategy.edit:
        class: Qissues\Interfaces\Console\Input\Strategy\Issue\EditStrategy
        arguments:
            - @console.input.external_editor
            - @console.input.active_format.issue

    console.input.issue_strategy.interactive:
        class: Qissues\Interfaces\Console\Input\Strategy\Issue\InteractiveStrategy

    console.input.issue_strategy.stdin:
        class: Qissues\Interfaces\Console\Input\Strategy\Issue\StdinStrategy
        arguments:
            - "php://stdin"
            - @console.input.format.json

    console.input.issue_strategy.option:
        class: Qissues\Interfaces\Console\Input\Strategy\Issue\OptionStrategy

    console.input.comment_strategy.option:
        class: Qissues\Interfaces\Console\Input\Strategy\Comment\OptionStrategy

    console.input.comment_strategy.edit:
        class: Qissues\Interfaces\Console\Input\Strategy\Comment\EditStrategy
        arguments:
            - @console.input.external_editor

    console.input.comment_strategy.stdin:
        class: Qissues\Interfaces\Console\Input\Strategy\Comment\StdinStrategy
        arguments:
            - "php://stdin"

    console.input.comment_strategy.interactive:
        class: Qissues\Interfaces\Console\Input\Strategy\Comment\InteractiveStrategy

    console.input.details_strategy.edit:
        class: Qissues\Interfaces\Console\Input\Strategy\Transition\EditStrategy
        arguments:
            - @console.input.external_editor
            - @console.input.active_format.details

    console.input.git_id:
        class: Qissues\Interfaces\Console\Input\GitId
        arguments:
            - @console.shell

    console.input.criteria_builder:
        class: Qissues\Interfaces\Console\Input\CriteriaBuilder

    console.input.report_criteria_builder:
        class: Qissues\Interfaces\Console\Input\ReportCriteriaBuilder

    console.input.external_editor:
        class: Qissues\Interfaces\Console\Input\ExternalFileEditor
        arguments:
            - @console.shell
            - @filesystem
            - %console.editor%
            - %console.tmp_file.prefix%

    console.input.format.factory:
        class: Qissues\Application\Input\FormatFactory
        arguments:
            - @container

    console.input.active_format.issue:
        class: Qissues\Interfaces\Console\Input\FileFormats\FileFormat
        factory_service: console.input.format.factory
        factory_method: getFormat
        arguments: ['issue']

    console.input.active_format.comment:
        class: Qissues\Interfaces\Console\Input\FileFormats\FileFormat
        factory_service: console.input.format.factory
        factory_method: getFormat
        arguments: ['comment']

    console.input.active_format.details:
        class: Qissues\Interfaces\Console\Input\FileFormats\FileFormat
        factory_service: console.input.format.factory
        factory_method: getFormat
        arguments: ['details']


    console.input.format.yaml:
        class: Qissues\Interfaces\Console\Input\FileFormats\YmlFormat
        arguments:
            - @yaml_parser
            - @yaml_builder

    console.input.format.frontmatter:
        class: Qissues\Interfaces\Console\Input\FileFormats\FrontMatterFormat
        arguments:
            - @frontmatter_parser

    console.input.format.json:
        class: Qissues\Interfaces\Console\Input\FileFormats\JsonFormat

    console.output.table_renderer:
        class: Qissues\Interfaces\Console\Output\Renderer\TableRenderer

    console.output.issue_views.standard:
        class: Qissues\Interfaces\Console\Output\View\Issue\StandardView

    console.output.issue_views.json:
        class: Qissues\Interfaces\Console\Output\View\Issue\JsonView
        arguments:
            - @model.issue_serializer
            - @model.comment_serializer

    console.output.issues_views.detailed:
        class: Qissues\Interfaces\Console\Output\View\IssuesList\DetailedView
        arguments:
            - @console.output.table_renderer

    console.output.issues_views.basic:
        class: Qissues\Interfaces\Console\Output\View\IssuesList\BasicView
        arguments:
            - @console.output.table_renderer

    console.output.issues_views.tiny:
        class: Qissues\Interfaces\Console\Output\View\IssuesList\TinyView
        arguments:
            - @console.output.spaced_table_renderer
            - %console.output.tinyview_priorities%
            - %console.output.tinyview_colors%

    console.output.issues_views.json:
        class: Qissues\Interfaces\Console\Output\View\IssuesList\JsonView
        arguments:
            - @model.issue_serializer

    console.output.spaced_table_renderer:
        class: Qissues\Interfaces\Console\Output\Renderer\SpacedTableRenderer

    console.output.browser:
        class: Qissues\Interfaces\Console\Output\WebBrowser
        arguments:
             - @console.shell
             - %console.browser.command%

    support.catalog_builder:
        class: Qissues\Trackers\Shared\Support\FeatureCatalogBuilder
        arguments:
            - %features%

    support.catalog:
        class: Qissues\Trackers\Shared\Support\FeatureCatalog
        factory_service: support.catalog_builder
        factory_method: "build"

    support.featureset_builder:
        class: Qissues\Application\Container\ArrayFeatureSetBuilder

    yaml_parser:
        class: Symfony\Component\Yaml\Parser

    yaml_builder:
        class: Symfony\Component\Yaml\Dumper

    frontmatter_parser:
        class: Qissues\Application\Input\FrontMatterParser
        arguments:
             - @yaml_parser

    filesystem:
        class: Qissues\System\Filesystem

    metadata.builder:
        class: Qissues\Trackers\Shared\Metadata\Builder
        arguments:
            - @system.storage
            - %tracker%
            - %mapping_class%

    metadata:
        class: Qissues\Trackers\Shared\Metadata\Metadata
        factory_service: metadata.builder
        factory_method: build

    basic_workflow:
        class: Qissues\Trackers\Shared\BasicWorkflow
        
