parameters:
    console.editor: "vim"
    console.tmp_file.prefix: "qissues"
    console.browser.command:
    console.input.default_strategy: "edit"

services:
    console.input.issue_strategy.edit:
        class: Qissues\Console\Input\Strategy\EditIssueStrategy
        arguments:
            - @console.input.external_editor
            - @console.input.format.frontmatter

    console.input.issue_strategy.interactive:
        class: Qissues\Console\Input\Strategy\InteractiveIssueStrategy


    console.input.git_id:
        class: Qissues\Console\Input\GitId

    console.input.criteria_builder:
        class: Qissues\Console\Input\CriteriaBuilder

    console.input.external_editor:
        class: Qissues\Console\Input\ExternalFileEditor
        arguments:
            - %console.editor%
            - %console.tmp_file.prefix%

    console.input.format.frontmatter:
        class: Qissues\Console\Input\FileFormats\FrontMatterFormat
        arguments:
            - @frontmatter_parser

    console.output.table_renderer:
        class: Qissues\Console\Output\TableRenderer

    console.output.views.single:
        class: Qissues\Console\Output\SingleView

    console.output.issues_views.detailed:
        class: Qissues\Console\Output\IssuesList\DetailedView
        arguments:
            - @console.output.table_renderer

    console.output.issues_views.basic:
        class: Qissues\Console\Output\IssuesList\BasicView
        arguments:
            - @console.output.table_renderer

    console.output.issues_views.tiny:
        class: Qissues\Console\Output\IssuesList\TinyView

    console.output.browser:
        class: Qissues\Console\Output\WebBrowser
        arguments:
             - %console.browser.command%

    support.catalog_builder:
        class: Qissues\Model\Tracker\Support\FeatureCatalogBuilder

    support.catalog:
        class: Qissues\Model\Tracker\Support\FeatureCatalog
        factory_service: support.catalog_builder
        factory_method: "build"

    yaml_parser:
        class: Symfony\Component\Yaml\Parser

    frontmatter_parser:
        class: Qissues\System\FrontMatterParser
        arguments:
             - @yaml_parser
