parameters:
    console.editor: "vim"
    console.tmp_file.prefix: "qissues"
    console.browser.command:
    console.input.default_strategy: "edit"
    console.input.default_format: "frontmatter"
    console.output.tinyview_priorities:
        5: '▲'
        4: '▴'
        3: '-'
        2: '▾'
        1: '▼'
    console.output.tinyview_colors:
        bug: "p5"

services:
    console.shell:
        class: Qissues\Console\Shell\BasicShell

    console.input.issue_strategy.edit:
        class: Qissues\Console\Input\Strategy\Issue\EditStrategy
        arguments:
            - @console.input.external_editor
            - @console.input.format.active

    console.input.issue_strategy.interactive:
        class: Qissues\Console\Input\Strategy\Issue\InteractiveStrategy

    console.input.issue_strategy.stdin:
        class: Qissues\Console\Input\Strategy\Issue\StdinStrategy
        arguments:
            - "php://stdin"
            - @console.input.format.active

    console.input.issue_strategy.option:
        class: Qissues\Console\Input\Strategy\Issue\OptionStrategy

    console.input.comment_strategy.option:
        class: Qissues\Console\Input\Strategy\Comment\OptionStrategy

    console.input.comment_strategy.edit:
        class: Qissues\Console\Input\Strategy\Comment\EditStrategy
        arguments:
            - @console.input.external_editor

    console.input.comment_strategy.stdin:
        class: Qissues\Console\Input\Strategy\Comment\StdinStrategy
        arguments:
            - "php://stdin"

    console.input.comment_strategy.interactive:
        class: Qissues\Console\Input\Strategy\Comment\InteractiveStrategy

    console.input.git_id:
        class: Qissues\Console\Input\GitId
        arguments:
            - @console.shell

    console.input.criteria_builder:
        class: Qissues\Console\Input\CriteriaBuilder

    console.input.report_criteria_builder:
        class: Qissues\Console\Input\ReportCriteriaBuilder

    console.input.external_editor:
        class: Qissues\Console\Input\ExternalFileEditor
        arguments:
            - %console.editor%
            - %console.tmp_file.prefix%

    console.input.format.factory:
        class: Qissues\System\FormatFactory
        arguments:
            - @container

    console.input.format.active:
        class: Qissues\Console\Input\FileFormats\FileFormat
        factory_service: console.input.format.factory
        factory_method: getFormat

    console.input.format.frontmatter:
        class: Qissues\Console\Input\FileFormats\FrontMatterFormat
        arguments:
            - @frontmatter_parser

    console.input.format.json:
        class: Qissues\Console\Input\FileFormats\JsonFormat

    console.output.table_renderer:
        class: Qissues\Console\Output\TableRenderer

    console.output.issue_views.standard:
        class: Qissues\Console\Output\Issue\StandardView

    console.output.issue_views.json:
        class: Qissues\Console\Output\Issue\JsonView

    console.output.issues_views.detailed:
        class: Qissues\Console\Output\IssuesList\DetailedView
        arguments:
            - @console.output.table_renderer

    console.output.issues_views.basic:
        class: Qissues\Console\Output\IssuesList\BasicView
        arguments:
            - @console.output.table_renderer

    console.output.issues_views.tiny:
        class: Qissues\Console\Output\IssuesList\TinyView
        arguments:
            - @console.output.spaced_table_renderer
            - %console.output.tinyview_priorities%
            - %console.output.tinyview_colors%

    console.output.issues_views.json:
        class: Qissues\Console\Output\IssuesList\JsonView

    console.output.spaced_table_renderer:
        class: Qissues\Console\Output\SpacedTableRenderer

    console.output.browser:
        class: Qissues\Console\Output\WebBrowser
        arguments:
             - %console.browser.command%

    support.catalog_builder:
        class: Qissues\Model\Tracker\Support\FeatureCatalogBuilder

    support.catalog:
        class: Qissues\Model\Tracker\Support\FeatureCatalog
        factory_service: support.catalog_builder
        factory_method: "build"

    yaml_parser:
        class: Symfony\Component\Yaml\Parser

    frontmatter_parser:
        class: Qissues\System\FrontMatterParser
        arguments:
             - @yaml_parser
