parameters:
    github.repository: "account/repo-name"
    github.username: "account"
    github.password: "password"
    bitbucket.repository: "account/repo-name"
    bitbucket.username: "account"
    bitbucket.password: "password"
    trello.key: "application/developer api key"
    trello.token: "oauth token"
    trello.board: "Board Name"
    jira.projectKey: "PROJ"
    jira.host: "subdomain.atlassian.net"
    jira.username: "account"
    jira.password: "password"

services:
    tracker.github:
        class: Qissues\Trackers\Shared\IssueTracker
        arguments:
            - @tracker.github.repository
            - @tracker.github.mapping
            - @tracker.github.features
            - @tracker.github.workflow

    tracker.github.repository:
        class: Qissues\Trackers\GitHub\GitHubRepository
        arguments:
            - %github.repository%
            - %github.username%
            - %github.password%
            - @tracker.github.mapping

    tracker.github.mapping:
        class: Qissues\Trackers\GitHub\GitHubMapping

    tracker.github.features:
        class: Qissues\Trackers\Shared\Support\FeatureSet
        factory_service: support.featureset_builder
        factory_method: build
        arguments:
             - @support.catalog
             -
                statuses: [single]
                labels: [multiple, dynamic]

    tracker.github.workflow:
        class: Qissues\Trackers\Shared\BasicWorkflow
        arguments:
            - @tracker.github.repository

    tracker.github.features_builder:
        class: Qissues\Trackers\GitHub\GitHubSupport

    tracker.bitbucket:
        class: Qissues\Trackers\Shared\IssueTracker
        arguments:
            - @tracker.bitbucket.repository
            - @tracker.bitbucket.mapping
            - @tracker.bitbucket.features
            - @tracker.bitbucket.workflow

    tracker.bitbucket.repository:
        class: Qissues\Trackers\BitBucket\BitBucketRepository
        arguments:
            - %bitbucket.repository%
            - %bitbucket.username%
            - %bitbucket.password%
            - @tracker.bitbucket.mapping

    tracker.bitbucket.mapping:
        class: Qissues\Trackers\BitBucket\BitBucketMapping

    tracker.bitbucket.features:
        class: Qissues\Trackers\Shared\Support\FeatureSet
        factory_service: support.featureset_builder
        factory_method: build
        arguments:
             - @support.catalog
             -
                statuses: [single]
                types: [single]
                labels: [multiple, dynamic]
                priorities: [single]

    tracker.bitbucket.features_builder:
        class: Qissues\Trackers\BitBucket\BitBucketSupport

    tracker.bitbucket.workflow:
        class: Qissues\Trackers\Shared\BasicWorkflow
        arguments:
            - @tracker.bitbucket.repository

    tracker.trello:
        class: Qissues\Trackers\Shared\IssueTracker
        arguments:
            - @tracker.trello.repository
            - @tracker.trello.mapping
            - @tracker.trello.features
            - @tracker.trello.workflow

    tracker.trello.repository:
        class: Qissues\Trackers\Trello\TrelloRepository
        arguments:
            - %trello.board%
            - %trello.key%
            - %trello.token%
            - @tracker.trello.mapping
            - @metadata

    tracker.trello.mapping:
        class: Qissues\Trackers\Trello\TrelloMapping
        arguments:
            - @metadata

    tracker.trello.metadata:
        class: Qissues\Trackers\Trello\TrelloMetadata

    tracker.trello.features:
        class: Qissues\Trackers\Shared\Support\FeatureSet
        factory_service: support.featureset_builder
        factory_method: build
        arguments:
             - @support.catalog
             -
                statuses: [single]
                labels: [multiple, dynamic]
                metadata: [dynamic]

    tracker.trello.workflow:
        class: Qissues\Trackers\Shared\BasicWorkflow
        arguments:
            - @tracker.trello.repository

    tracker.jira:
        class: Qissues\Trackers\Shared\IssueTracker
        arguments:
            - @tracker.jira.repository
            - @tracker.jira.mapping
            - @tracker.jira.features
            - @tracker.jira.workflow

    tracker.jira.repository:
        class: Qissues\Trackers\Jira\JiraRepository
        arguments:
            - %jira.host%
            - %jira.projectKey%
            - %jira.username%
            - %jira.password%
            - @tracker.jira.mapping

    tracker.jira.mapping:
        class: Qissues\Trackers\Jira\JiraMapping
        arguments:
            - @metadata
            - @tracker.jira.jql

    tracker.jira.metadata:
        class: Qissues\Trackers\Jira\JiraMetadata

    tracker.jira.jql:
        class: Qissues\Trackers\Jira\JqlQueryBuilder
        arguments:
            - @metadata

    tracker.jira.features:
        class: Qissues\Trackers\Shared\Support\FeatureSet
        factory_service: support.featureset_builder
        factory_method: build
        arguments:
            - @support.catalog
            -
                statuses: [single]
                types: [single]
                labels: [multiple, dynamic]
                priorities: [single]

    tracker.jira.workflow:
        class: Qissues\Trackers\Jira\JiraWorkflow
        arguments:
            - @tracker.jira.repository
