parameters:
    github.repository: "account/repo-name"
    github.username: "account"
    github.password: "password"
    bitbucket.repository: "account/repo-name"
    bitbucket.username: "account"
    bitbucket.password: "password"
    trello.key: "application/developer api key"
    trello.token: "oauth token"
    trello.board: "Board Name"

services:
    tracker.github:
        class: Qissues\Model\Tracker\IssueTracker
        arguments:
            - @tracker.github.repository
            - @tracker.github.mapping
            - @tracker.github.features

    tracker.github.repository:
        class: Qissues\Trackers\GitHub\GitHubRepository
        arguments:
            - %github.repository%
            - %github.username%
            - %github.password%
            - @tracker.github.mapping

    tracker.github.mapping:
        class: Qissues\Trackers\GitHub\GitHubMapping

    tracker.github.features:
        class: Qissues\Model\Tracker\Support\FeatureSet
        factory_service: tracker.github.features_builder
        factory_method: buildFor
        arguments:
             - @support.catalog

    tracker.github.features_builder:
        class: Qissues\Trackers\GitHub\GitHubSupport


    tracker.bitbucket:
        class: Qissues\Model\Tracker\IssueTracker
        arguments:
            - @tracker.bitbucket.repository
            - @tracker.bitbucket.mapping
            - @tracker.bitbucket.features

    tracker.bitbucket.repository:
        class: Qissues\Trackers\BitBucket\BitBucketRepository
        arguments:
            - %bitbucket.repository%
            - %bitbucket.username%
            - %bitbucket.password%
            - @tracker.bitbucket.mapping

    tracker.bitbucket.mapping:
        class: Qissues\Trackers\BitBucket\BitBucketMapping

    tracker.bitbucket.features:
        class: Qissues\Model\Tracker\Support\FeatureSet
        factory_service: tracker.bitbucket.features_builder
        factory_method: buildFor
        arguments:
             - @support.catalog

    tracker.bitbucket.features_builder:
        class: Qissues\Trackers\BitBucket\BitBucketSupport

    tracker.trello:
        class: Qissues\Model\Tracker\IssueTracker
        arguments:
            - @tracker.trello.repository
            - @tracker.trello.mapping
            - @tracker.trello.features

    tracker.trello.repository:
        class: Qissues\Trackers\Trello\TrelloRepository
        arguments:
            - %trello.board%
            - %trello.key%
            - %trello.token%
            - @tracker.trello.metadata
            - @tracker.trello.mapping

    tracker.trello.mapping:
        class: Qissues\Trackers\Trello\TrelloMapping
        arguments:
            - @tracker.trello.metadata

    tracker.trello.features:
        class: Qissues\Model\Tracker\Support\FeatureSet
        factory_service: tracker.trello.features_builder
        factory_method: buildFor
        arguments:
             - @support.catalog

    tracker.trello.features_builder:
        class: Qissues\Trackers\Trello\TrelloSupport

    tracker.trello.metadata:
        class: Qissues\Trackers\Trello\TrelloMetadataBuilder
        arguments:
            - %trello.board%
            - %trello.key%
            - %trello.token%
            - @system.storage


