parameters:
    github.repository:
    github.username:
    github.password:

services:
    tracker.github:
        class: Qissues\Model\Tracker\IssueTracker
        arguments:
            - @tracker.github.repository
            - @tracker.github.mapping
            - @tracker.github.features

    tracker.github.repository:
        class: Qissues\Trackers\GitHub\GitHubRepository
        arguments:
            - %github.repository%
            - %github.username%
            - %github.password%
            - @tracker.github.mapping

    tracker.github.mapping:
        class: Qissues\Trackers\GitHub\GitHubMapping

    tracker.github.features:
        class: Qissues\Model\Tracker\Support\FeatureSet
        factory_service: tracker.github.features_builder
        factory_method: buildFor
        arguments:
             - @support.catalog

    tracker.github.features_builder:
        class: Qissues\Trackers\GitHub\GitHubSupport
